@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>CfnNagReportReader\n<size:10>com.hack23.sonar.cloudformation.parser" as com.hack23.sonar.cloudformation.parser.CfnNagReportReader [[CfnNagReportReader.html]] {
        +readReport(InputStream): CfnNagReport
    }

    center footer UMLDoclet 2.0.3-SNAPSHOT, PlantUML 1.2019.06
@enduml
