@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>CloudformationConstants\n<size:10>com.hack23.sonar.cloudformation" as com.hack23.sonar.cloudformation.CloudformationConstants [[CloudformationConstants.html]] {
        {static} +REPORT_FILES_PROPERTY: String
    }

    center footer UMLDoclet 2.0.3-SNAPSHOT, PlantUML 1.2019.06
@enduml
